    name: Vérification PEP 8

    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main
    permissions:
      contents: read

    jobs:
      lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Configuration de Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Installation des dépendances de linting
          run: |
            python -m pip install --upgrade pip
            pip install flake8
        - name: Exécution de Flake8
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    
